version: '3.4'

services:
  materialdashboardangular:
    image: materialdashboardangular
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
